// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ievqnwbaaultykcbxltp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlldnFud2JhYXVsdHlrY2J4bHRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg5NDUxMDksImV4cCI6MjA1NDUyMTEwOX0.vnQxkh-9IR72CjtyGxo2qy1-I0vZtINlzh3cxUioLnw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);